all:
	g++ -std=c++11 main.cpp parser.cpp debug.cpp record.cpp util.cpp cryptoUtil.cpp -w -o txblk  -L/cise/homes/nemo/bin/ssl/openssl/lib -lssl -lcrypto -ldl -I/cise/homes/nemo/bin/ssl/openssl/include
clean:
	rm -f txblk
